-- 3학년 11반 웹사이트용 Supabase 초기 설정
-- Supabase Dashboard > SQL Editor에서 이 파일 전체를 한 번 실행하세요.

create table if not exists public.notices (
    id bigint generated by default as identity primary key,
    title text not null check (char_length(title) between 1 and 80),
    content text not null check (char_length(content) between 1 and 5000),
    author_role text not null check (author_role in ('담임 선생님', '회장', '부회장')),
    pinned boolean not null default false,
    created_at timestamptz not null default now()
);

create table if not exists public.suggestions (
    id bigint generated by default as identity primary key,
    category text not null check (char_length(category) between 1 and 30),
    title text not null check (char_length(title) between 1 and 80),
    content text not null check (char_length(content) between 1 and 2500),
    lookup_hash text not null unique check (char_length(lookup_hash) = 64),
    status text not null default '접수'
        check (status in ('접수', '확인 중', '논의 중', '반영 완료', '답변 완료', '보류')),
    reply text not null default '' check (char_length(reply) <= 2000),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.study_posts (
    id bigint generated by default as identity primary key,
    subject text not null check (char_length(subject) between 1 and 20),
    title text not null check (char_length(title) between 1 and 80),
    difficulty text not null check (difficulty in ('가볍게', '보통', '도전')),
    problem text not null check (char_length(problem) between 1 and 4000),
    solution text not null check (char_length(solution) between 1 and 6000),
    source text not null default '' check (char_length(source) <= 120),
    author_alias text not null default '익명' check (char_length(author_alias) <= 20),
    problem_image_url text not null default '',
    problem_image_path text not null default '',
    solution_image_url text not null default '',
    solution_image_path text not null default '',
    created_at timestamptz not null default now()
);

create index if not exists notices_pinned_created_idx
    on public.notices (pinned desc, created_at desc);
create index if not exists suggestions_created_idx
    on public.suggestions (created_at desc);
create index if not exists study_posts_created_idx
    on public.study_posts (created_at desc);
create index if not exists study_posts_subject_idx
    on public.study_posts (subject);

-- 브라우저가 데이터베이스에 직접 접근하지 못하도록 공개 정책을 두지 않습니다.
-- Streamlit 서버의 service_role 키만 아래 테이블을 읽고 씁니다.
alter table public.notices enable row level security;
alter table public.suggestions enable row level security;
alter table public.study_posts enable row level security;

grant all on table public.notices to service_role;
grant all on table public.suggestions to service_role;
grant all on table public.study_posts to service_role;
grant usage, select on all sequences in schema public to service_role;

-- 문제/풀이 이미지는 공개 게시물에 표시되므로 공개 버킷에 저장합니다.
insert into storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
)
values (
    'study-images',
    'study-images',
    true,
    4194304,
    array['image/webp']::text[]
)
on conflict (id) do update set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

